### ISSUE TITLE
Allow specifying which schemes you want in validation.

### ISSUE THREAD

**Issue by dstufft** [sigmavirus24/rfc3986#17]
Right now if you want to validate that an URI is valid and it has one of a set of schemes you have to parse the URI, check it's validity, then manually check the scheme. It'd be nice to be able to just do it all in one go, something like:

``` python
# Require schemes, but doesn't matter which.
is_valid_uri("...", require_scheme=True)

# Require schemes, and must be either http or https.
is_valid_uri("...", require_scheme={"http", "https"})
```

**Comment by sigmavirus24** [comment]
I'm changing this with #25. It's likely too late, but hopefully it will help.

**Comment by dstufft** [comment]
Well, it'd let me remove [this code](https://github.com/pypa/warehouse/blob/54e59eab93be8aee21d96d993b64bf53272b9087/warehouse/utils/http.py#L55-L67) :D

**Comment by sigmavirus24** [comment]
So that should look like:

```py
validator = rfc3986.validators.Validator().require_presence_of(
    'scheme'
).allow_schemes('http', 'https).allow_hosts(
    ...
)
validator.validate(uri)
```
