### ISSUE TITLE
Update for RFC 6874 (Zone Identifiers in IPv6 addresses)

### ISSUE THREAD

**Issue by sigmavirus24** [sigmavirus24/rfc3986#2]
https://tools.ietf.org/html/rfc6874

**Comment by littypreeth** [comment]
Hi
We needed to use LL IPS for doing initial configs of host/VM and coz of this we are stuck. Is there anything I can help with to accelerate the fix of this?

**Comment by sigmavirus24** [comment]
If your employer would be willing to sponsor this via BountySource I'd be happy to set that up.
