### ISSUE TITLE
rfc3986 cannot be installed on Python 3 with locale encoding different than UTF-8

### ISSUE THREAD

**Issue by haypo** [sigmavirus24/rfc3986#20]
This bug was already fixed 3 months ago by the pull request #14 (commit cf153730584853e003f71a3efb9aa1aef4d2d3c7). The problem is that no new release was done since this commit was merge. Can you please release a new version?

By the way, since the project doesn't need 2to3 or other hack to support Python 2 and Python 3, it looks like rfc3986 works well on Python 3 without any change and that you can release an "universal wheel": a single binary package for Python 2 and Python 3. Or at least, please upload also a wheel package for Python 3.

**Comment by sigmavirus24** [comment]
0.3.0 was just released

**Comment by haypo** [comment]
Cool, thanks :-)

FYI it looks like you have an issue with reST syntax in README: https://pypi.python.org/pypi/rfc3986

**Comment by sigmavirus24** [comment]
Sorry it took me so long to remember to do the release. I'm unconcerned with the reST syntax personally. `¯\_(ツ)_/¯`
