### ISSUE TITLE
document how to remove components (using copy_with()?)

### ISSUE THREAD

**Issue by wbolster** [sigmavirus24/rfc3986#22]
Is the `copy_with()` method combined with empty strings (note that `None` doesn't work) the correct way to remove components like a fragment altogether?

``` python
>>> s = 'http://example.org/?this-is-the-query#this-is-the-fragment'
>>> rfc3986.uri_reference(s).copy_with(fragment='').unsplit()
'http://example.org/?this-is-the-query
```

If so, this may be worth mentioning in the docs. If not, please point me to the proper approach. :)

**Comment by sigmavirus24** [comment]
There aren't really docs :/ This will be noted there.

Thanks @wbolster!

**Comment by wbolster** [comment]
Yeah I get that I'll have to do with the README and docstrings, but I was also wondering whether "pass an empty string to `copy_with()`" is the correct way to remove components?

**Comment by sigmavirus24** [comment]
That is the correct way. See https://github.com/sigmavirus24/rfc3986#replacing-urlparse

`None` is the default value for [`copy_with`](https://github.com/sigmavirus24/rfc3986/blob/master/rfc3986/parseresult.py#L130). We could do something like:

```py
# rfc3986/misc.py
UseExisting = object()
```

```py
# rfc3986/parseresult.py
def copy_with(self, scheme=misc.UseExisting, userinfo=misc.UseExisting, ...):
    # ...
    for name, value in attributes:
        if value is misc.UseExisting:
            value = getattr(self, name)
    # ...
```

```py
# rfc3986/uri.py
def copy_with(self, scheme=misc.UseExisting, ...):
    attributes = { ... }
    for key, value in list(attributes.items()):
        if value is misc.UseExisting:
            del attributes[key]
    return self._replace(**attributes)
```

Being able to pass `None` makes sense to me instead of having to use `''`.

**Comment by wbolster** [comment]
Yeah, or require `**kwarg` and do some `dict` dancing, but that won't result in nice docstrings.

**Comment by sigmavirus24** [comment]
I specifically want to avoid `**kwargs` for these.
